const products = [
  {
    id: 1,
    title: "iPhone 15 Pro",
    description: "Найновіший флагман Apple з потужним процесором A17 Pro.",
    price: 1299,
    discountPercentage: 8.2,
    rating: 4.9,
    stock: 50,
    brand: "Apple",
    category: "smartphones",
    thumbnail: "https://cdn.dummyjson.com/product-images/1/thumbnail.jpg",
  },
  {
    id: 2,
    title: "Samsung Galaxy S24 Ultra",
    description: "Флагман Samsung з камерою 200 Мп і стилусом S-Pen.",
    price: 1399,
    discountPercentage: 9.1,
    rating: 4.8,
    stock: 70,
    brand: "Samsung",
    category: "smartphones",
    thumbnail: "https://cdn.dummyjson.com/product-images/2/thumbnail.jpg",
  },
  {
    id: 3,
    title: "Xiaomi 14 Pro",
    description: "Потужний Android-смартфон з процесором Snapdragon 8 Gen 3.",
    price: 899,
    discountPercentage: 12.5,
    rating: 4.6,
    stock: 100,
    brand: "Xiaomi",
    category: "smartphones",
    thumbnail: "https://cdn.dummyjson.com/product-images/3/thumbnail.jpg",
  },
  {
    id: 4,
    title: "Google Pixel 8",
    description: "Телефон від Google з відмінною камерою та чистим Android.",
    price: 849,
    discountPercentage: 7.4,
    rating: 4.7,
    stock: 60,
    brand: "Google",
    category: "smartphones",
    thumbnail: "https://cdn.dummyjson.com/product-images/4/thumbnail.jpg",
  },
  {
    id: 5,
    title: "OnePlus 12",
    description: "Швидкий смартфон із SuperVOOC зарядкою 100W.",
    price: 749,
    discountPercentage: 10.0,
    rating: 4.5,
    stock: 80,
    brand: "OnePlus",
    category: "smartphones",
    thumbnail: "https://cdn.dummyjson.com/product-images/5/thumbnail.jpg",
  },
  {
    id: 6,
    title: "MacBook Air M3",
    description: "Легкий ноутбук Apple на новому чіпі M3.",
    price: 1399,
    discountPercentage: 6.0,
    rating: 4.9,
    stock: 40,
    brand: "Apple",
    category: "laptops",
    thumbnail: "https://cdn.dummyjson.com/product-images/6/thumbnail.png",
  },
  {
    id: 7,
    title: "Dell XPS 15",
    description: "Преміальний ноутбук для роботи й творчості.",
    price: 1799,
    discountPercentage: 7.2,
    rating: 4.7,
    stock: 35,
    brand: "Dell",
    category: "laptops",
    thumbnail: "https://cdn.dummyjson.com/product-images/7/thumbnail.jpg",
  },
  {
    id: 8,
    title: "Asus ROG Zephyrus",
    description: "Ігровий ноутбук із відеокартою RTX 4080.",
    price: 2499,
    discountPercentage: 5.5,
    rating: 4.8,
    stock: 25,
    brand: "Asus",
    category: "laptops",
    thumbnail: "https://cdn.dummyjson.com/product-images/8/thumbnail.jpg",
  },
  {
    id: 9,
    title: "Lenovo ThinkPad X1 Carbon",
    description: "Надійний бізнес-ноутбук преміум-класу.",
    price: 1599,
    discountPercentage: 9.0,
    rating: 4.6,
    stock: 50,
    brand: "Lenovo",
    category: "laptops",
    thumbnail: "https://cdn.dummyjson.com/product-images/9/thumbnail.jpg",
  },
  {
    id: 10,
    title: "HP Spectre x360",
    description: "Ультрабук-трансформер з сенсорним екраном.",
    price: 1399,
    discountPercentage: 8.5,
    rating: 4.7,
    stock: 45,
    brand: "HP",
    category: "laptops",
    thumbnail: "https://cdn.dummyjson.com/product-images/10/thumbnail.jpg",
  },
  {
    id: 11,
    title: "iPad Pro 12.9” M2",
    description: "Планшет з чіпом M2 — потужний як ноутбук.",
    price: 1199,
    discountPercentage: 5.2,
    rating: 4.9,
    stock: 30,
    brand: "Apple",
    category: "tablets",
    thumbnail: "https://cdn.dummyjson.com/product-images/11/thumbnail.jpg",
  },
  {
    id: 12,
    title: "Samsung Galaxy Tab S9 Ultra",
    description: "Великий AMOLED-дисплей, підтримка стилуса S-Pen.",
    price: 1099,
    discountPercentage: 6.3,
    rating: 4.8,
    stock: 35,
    brand: "Samsung",
    category: "tablets",
    thumbnail: "https://cdn.dummyjson.com/product-images/12/thumbnail.jpg",
  },
  {
    id: 13,
    title: "Lenovo Tab P12 Pro",
    description: "Якісний Android-планшет для мультимедіа.",
    price: 749,
    discountPercentage: 10.5,
    rating: 4.6,
    stock: 60,
    brand: "Lenovo",
    category: "tablets",
    thumbnail: "https://cdn.dummyjson.com/product-images/13/thumbnail.jpg",
  },
  {
    id: 14,
    title: "Xiaomi Pad 6",
    description: "Доступний і потужний планшет із Snapdragon 870.",
    price: 499,
    discountPercentage: 12.3,
    rating: 4.5,
    stock: 80,
    brand: "Xiaomi",
    category: "tablets",
    thumbnail: "https://cdn.dummyjson.com/product-images/14/thumbnail.jpg",
  },
  {
    id: 15,
    title: "Huawei MatePad Pro",
    description: "Тонкий планшет із підтримкою M-Pencil.",
    price: 699,
    discountPercentage: 9.1,
    rating: 4.6,
    stock: 50,
    brand: "Huawei",
    category: "tablets",
    thumbnail: "https://cdn.dummyjson.com/product-images/15/thumbnail.jpg",
  },
  {
    id: 16,
    title: "Apple Watch Series 9",
    description: "Смарт-годинник із сенсором температури та відстеженням здоров’я.",
    price: 499,
    discountPercentage: 7.0,
    rating: 4.8,
    stock: 70,
    brand: "Apple",
    category: "smartwatches",
    thumbnail: "https://cdn.dummyjson.com/product-images/16/thumbnail.jpg",
  },
  {
    id: 17,
    title: "Samsung Galaxy Watch 6",
    description: "Стильний годинник на Wear OS з безліччю функцій.",
    price: 399,
    discountPercentage: 6.8,
    rating: 4.7,
    stock: 80,
    brand: "Samsung",
    category: "smartwatches",
    thumbnail: "https://cdn.dummyjson.com/product-images/17/thumbnail.jpg",
  },
  {
    id: 18,
    title: "Xiaomi Watch S1",
    description: "Класичний дизайн і точне відстеження тренувань.",
    price: 249,
    discountPercentage: 10.0,
    rating: 4.5,
    stock: 90,
    brand: "Xiaomi",
    category: "smartwatches",
    thumbnail: "https://cdn.dummyjson.com/product-images/18/thumbnail.jpg",
  },
  {
    id: 19,
    title: "Garmin Fenix 7",
    description: "Професійний годинник для спорту та туризму.",
    price: 799,
    discountPercentage: 5.9,
    rating: 4.9,
    stock: 40,
    brand: "Garmin",
    category: "smartwatches",
    thumbnail: "https://cdn.dummyjson.com/product-images/19/thumbnail.jpg",
  },
  {
    id: 20,
    title: "Huawei Watch GT 4",
    description: "Елегантний дизайн і довга автономність.",
    price: 349,
    discountPercentage: 9.3,
    rating: 4.7,
    stock: 75,
    brand: "Huawei",
    category: "smartwatches",
    thumbnail: "https://cdn.dummyjson.com/product-images/20/thumbnail.jpg",
  },
  {
    id: 21,
    title: "AirPods Pro 2",
    description: "Навушники з активним шумозаглушенням.",
    price: 299,
    discountPercentage: 5.5,
    rating: 4.9,
    stock: 90,
    brand: "Apple",
    category: "earphones",
    thumbnail: "https://cdn.dummyjson.com/product-images/21/thumbnail.jpg",
  },
  {
    id: 22,
    title: "Samsung Galaxy Buds 2 Pro",
    description: "Комфортні TWS-навушники з якісним звуком.",
    price: 229,
    discountPercentage: 8.3,
    rating: 4.7,
    stock: 100,
    brand: "Samsung",
    category: "earphones",
    thumbnail: "https://cdn.dummyjson.com/product-images/22/thumbnail.jpg",
  },
  {
    id: 23,
    title: "Sony WH-1000XM5",
    description: "Преміальні накладні навушники з шумопоглинанням.",
    price: 399,
    discountPercentage: 6.1,
    rating: 4.9,
    stock: 55,
    brand: "Sony",
    category: "earphones",
    thumbnail: "https://cdn.dummyjson.com/product-images/23/thumbnail.jpg",
  },
  {
    id: 24,
    title: "JBL Tune 760NC",
    description: "Зручні бездротові навушники з глибоким басом.",
    price: 149,
    discountPercentage: 10.0,
    rating: 4.5,
    stock: 120,
    brand: "JBL",
    category: "earphones",
    thumbnail: "https://cdn.dummyjson.com/product-images/24/thumbnail.jpg",
  },
  {
    id: 25,
    title: "Beats Studio Pro",
    description: "Справжній студійний звук у стильному корпусі.",
    price: 349,
    discountPercentage: 7.0,
    rating: 4.6,
    stock: 80,
    brand: "Beats",
    category: "earphones",
    thumbnail: "https://cdn.dummyjson.com/product-images/25/thumbnail.jpg",
  },
  {
    id: 26,
    title: "Apple MagSafe Charger",
    description: "Бездротова зарядка для iPhone і AirPods.",
    price: 59,
    discountPercentage: 5.0,
    rating: 4.7,
    stock: 200,
    brand: "Apple",
    category: "accessories",
    thumbnail: "https://cdn.dummyjson.com/product-images/26/thumbnail.jpg",
  },
  {
    id: 27,
    title: "Samsung 45W Charger",
    description: "Швидка зарядка для сучасних смартфонів Galaxy.",
    price: 49,
    discountPercentage: 8.0,
    rating: 4.6,
    stock: 150,
    brand: "Samsung",
    category: "accessories",
    thumbnail: "https://cdn.dummyjson.com/product-images/27/thumbnail.jpg",
  },
  {
    id: 28,
    title: "Xiaomi Power Bank 20000mAh",
    description: "Потужний павербанк для подорожей.",
    price: 39,
    discountPercentage: 10.0,
    rating: 4.5,
    stock: 180,
    brand: "Xiaomi",
    category: "accessories",
    thumbnail: "https://cdn.dummyjson.com/product-images/28/thumbnail.jpg",
  },
  {
    id: 29,
    title: "Logitech MX Master 3S",
    description: "Професійна бездротова миша для роботи.",
    price: 119,
    discountPercentage: 7.4,
    rating: 4.9,
    stock: 60,
    brand: "Logitech",
    category: "accessories",
    thumbnail: "https://cdn.dummyjson.com/product-images/29/thumbnail.jpg",
  },
  {
    id: 30,
    title: "Razer Huntsman V2",
    description: "Ігрова клавіатура з оптичними перемикачами.",
    price: 199,
    discountPercentage: 6.2,
    rating: 4.8,
    stock: 70,
    brand: "Razer",
    category: "accessories",
    thumbnail: "https://cdn.dummyjson.com/product-images/30/thumbnail.jpg",
  }
];

const container = document.getElementById("productsContainer");

products.forEach(product => {
  const card = document.createElement("div");
  card.classList.add("product-card");

  card.innerHTML = `
    <img src="${product.thumbnail}" alt="${product.title}">
    <div class="product-info">
      <h3>${product.title}</h3>
      <p>${product.description}</p>
      <p class="price">$${product.price}</p>
      <p><strong>Рейтинг:</strong> ${product.rating} ⭐</p>
    </div>
    <div class="bottom-bar">
      <span>${product.brand}</span>
      <button class="cart-btn" data-id="${product.id}">🛒 До кошика</button>
    </div>
  `;

  container.appendChild(card);
});

document.addEventListener("click", (event) => {
  if (event.target.classList.contains("cart-btn")) {
    const productId = event.target.getAttribute("data-id");
    console.log("🛍 Додано товар з ID:", productId);
  }
});
